spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC&charsetEncoding=utf-8
    username: root
    password: 666666

mybatis:
  mapper-locations: classpath:mapper/*.xml


